[build]
  publish = "dist"  # O diretório onde o Astro gera o build
  command = "npm run build"  # O comando para gerar o build do seu site

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
